### ISSUE TITLE
NullPointerException thrown when appending text to TextArea

### ISSUE THREAD

**Issue by schrepfler** [scalafx/scalafx#316]
I've noticed I'm reaching concurrent or too quick situations when `TextArea.appendText` manages to break the component and no further appends get picked up. Any standard ways to mitigate these circumstances?

```java
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.text.PrismTextLayout.addTextRun(PrismTextLayout.java:755)
	at com.sun.javafx.text.GlyphLayout.addTextRun(GlyphLayout.java:140)
	at com.sun.javafx.text.GlyphLayout.breakRuns(GlyphLayout.java:210)
	at com.sun.javafx.text.PrismTextLayout.buildRuns(PrismTextLayout.java:770)
	at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1021)
	at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223)
	at com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:246)
	at javafx.scene.text.Text.getLogicalBounds(Text.java:358)
	at javafx.scene.text.Text.impl_computeGeomBounds(Text.java:1168)
	at javafx.scene.Node.updateGeomBounds(Node.java:3577)
	at javafx.scene.Node.getGeomBounds(Node.java:3530)
	at javafx.scene.Node.getLocalBounds(Node.java:3478)
	at javafx.scene.Node$MiscProperties$2.computeBounds(Node.java:6472)
	at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9306)
	at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9276)
	at javafx.scene.Node.getBoundsInLocal(Node.java:3156)
	at com.sun.javafx.scene.control.skin.TextAreaSkin$ContentView.layoutChildren(TextAreaSkin.java:207)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by jpsacha** [comment]
There is no ScalaFX in this stack trace. Do you code to reproduce this?

**Comment by jpsacha** [comment]
There is a a very similar question on StackOverflow: https://stackoverflow.com/questions/30863862/javafx-append-text-to-textarea-throws-exception

The quick answer is "FX textarea must be accessed on FX thread". This a general rule: update FX controls on FX thread only, including properties that are bound to those controls.
