### ISSUE TITLE
NPE exception running scalafx.controls.TextAreaTest in scala3

### ISSUE THREAD

**Issue by philwalk** [scalafx/scalafx#410]
While testing scalafx-demos_3-22.0.0-R34-SNAPSHOT with scala3, I have been largely successful, but am encountering what appears to be a circular definition problem (I'm not very familar with `scalafx`, so that could be a bad guess).

The NPE is at TextAreaTest.scala:48
[```scala prefHeight <== stage.scene().height```](https://github.com/scalafx/scalafx/blob/9d55921ad7ee1a6cdf72fcc222e45d52b5d3880c/scalafx-demos/src/main/scala/scalafx/controls/TextAreaTest.scala#L48)
Unless there's some non-obvious laziness going on, it seems that `scene` hasn't been initialized at this point.

```sh
scala -version
Scala code runner version 3.4.2 -- Copyright 2002-2024, LAMP/EPFL
```

Here is my command line (the classpath definition is below):
```scala
scala @/tmp/scalafxAtfile scalafx-demos/src/main/scala/scalafx/controls/TextAreaTest.scala
```
Here's the resulting stackdump
```scala
May 25, 2024 10:49:55 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1c0e866b'
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "scalafx.application.JFXApp3$PrimaryStage.scene()" because the return value of "scalafx.controls.TextAreaTest$.stage()" is null
        at scalafx.controls.TextAreaTest$$anon$2.<init>(TextAreaTest.scala:48)
        at scalafx.controls.TextAreaTest$.start(TextAreaTest.scala:52)
        at scalafx.application.JFXApp3.main$$anonfun$1(JFXApp3.scala:313)
        at scalafx.application.JFXApp3.init$$anonfun$1(JFXApp3.scala:328)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scalafx.application.JFXApp3.init(JFXApp3.scala:328)
        at scalafx.application.JFXApp3.init$(JFXApp3.scala:263)
        at scalafx.controls.TextAreaTest$.init(TextAreaTest.scala:41)
        at scalafx.application.AppHelper3.start(AppHelper3.scala:33)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
        ... 1 more
[2]-  Exit 1                  $EDITOR ${_RC-} "${args[@]}" 2> /dev/null
```
<details>
<summary>classpath definition</summary>
-cp /home/philwalk/workspace/scalafx/scalafx-demos/target/scala-3.3.3/scalafx-demos_3-22.0.0-R34-SNAPSHOT.jar:/home/philwalk/workspace/scalafx/scalafx/target/scala-3.3.3/scalafx_3-22.0.0-R34-SNAPSHOT.jar:/home/philwalk/workspace/scalafx/scalafx/target/scala-3.3.3/classes:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.3/scala3-library_3-3.3.3.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-base/22/javafx-base-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-controls/22/javafx-controls-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-fxml/22/javafx-fxml-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-graphics/22/javafx-graphics-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-media/22/javafx-media-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-swing/22/javafx-swing-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-web/22/javafx-web-22.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-base/22/javafx-base-22-linux.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-controls/22/javafx-controls-22-linux.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-fxml/22/javafx-fxml-22-linux.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-graphics/22/javafx-graphics-22-linux.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-media/22/javafx-media-22-linux.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-swing/22/javafx-swing-22-linux.jar:/home/philwalk/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjfx/javafx-web/22/javafx-web-22-linux.jar
</details>

Perhaps related, I also see an NPE exception here:
https://github.com/scalafx/scalafx/blob/9d55921ad7ee1a6cdf72fcc222e45d52b5d3880c/scalafx-demos/src/main/scala/scalafx/event/MultipleShapeDrawingDemo.scala#L128
but only if I click on the square before doing anything else (it's already preselected).
<details>
<summary>NPE Error Stackdump</summary>
<pre>
+ scala @/tmp/scalafxAtfile scalafx-demos/src/main/scala/scalafx/event/MultipleShapeDrawingDemo.scala
May 25, 2024 4:28:50 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @388c738d'
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "scalafx.scene.control.ToggleButton.id()" because the return value of "scalafx.Includes$.jfxToggleButton2sfx(javafx.scene.control.ToggleButton)" is null
        at scalafx.event.MultipleShapeDrawingDemo$$anon$8.$init$$$anonfun$1(MultipleShapeDrawingDemo.scala:128)
        at scalafx.event.MultipleShapeDrawingDemo$$anon$8.$init$$$anonfun$adapted$1(MultipleShapeDrawingDemo.scala:145)
        at scala.Function0.apply$mcV$sp(Function0.scala:42)
        at scalafx.beans.value.ObservableValue$$anon$3.changed(ObservableValue.scala:147)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:372)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
        at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.scene.control.ToggleGroup$3.set(ToggleGroup.java:146)
        at javafx.scene.control.ToggleGroup$3.set(ToggleGroup.java:128)
        at javafx.scene.control.ToggleGroup.clearSelectedToggle(ToggleGroup.java:191)
        at javafx.scene.control.ToggleButton$1.invalidated(ToggleButton.java:174)
        at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.scene.control.ToggleButton.setSelected(ToggleButton.java:151)
        at javafx.scene.control.ToggleButton.fire(ToggleButton.java:262)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3985)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1891)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2709)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:840)
</pre>
</details>

**Comment by jpsacha** [comment]
Fixed with #411
