### ISSUE TITLE
Simple JFXApp3 application not running if javafx-media is exluded

### ISSUE THREAD

**Issue by RumbleTumbleKid** [scalafx/scalafx#419]
I usually exclude transitive dependencies if they're not needed to reduce runtime image size. A simple JFXApp3 won't run if `javafx-media` is excluded even though it is not really needed.

```scala
//> using dep "org.scalafx::scalafx::23.0.1-R34,exclude=org.openjfx%javafx-media"

import scalafx.application.JFXApp3
import scalafx.scene.Scene
import scalafx.scene.layout.VBox
import scalafx.scene.control.Label
import scalafx.geometry.Pos.Center

object Main extends JFXApp3:
  override def start(): Unit =
    stage = new JFXApp3.PrimaryStage:
      width  = 640
      height = 480
      scene  = new Scene:
        root = new VBox:
          alignment = Center
          children  = Label("Hello World")
```

results in error:
```
com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @38a79d0e'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.NoClassDefFoundError: javafx/scene/media/MediaPlayer$Status
        at scalafx.delegate.AlignmentDelegate.alignment(AlignmentDelegate.scala:64)
        at scalafx.delegate.AlignmentDelegate.alignment$(AlignmentDelegate.scala:58)
        at scalafx.scene.layout.VBox.alignment(VBox.scala:78)
        at scalafx.delegate.AlignmentDelegate.alignment_$eq(AlignmentDelegate.scala:67)
        at scalafx.delegate.AlignmentDelegate.alignment_$eq$(AlignmentDelegate.scala:58)
        at scalafx.scene.layout.VBox.alignment_$eq(VBox.scala:78)
        at Main$$anon$3.<init>(Main.scala:15)
        at Main$$anon$2.<init>(Main.scala:16)
        at Main$$anon$1.<init>(Main.scala:16)
        at Main$.start(Main.scala:16)
        at scalafx.application.JFXApp3.main$$anonfun$1(JFXApp3.scala:318)
        at scalafx.application.JFXApp3.init$$anonfun$1(JFXApp3.scala:334)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
        at scalafx.application.JFXApp3.init(JFXApp3.scala:334)
        at scalafx.application.JFXApp3.init$(JFXApp3.scala:264)
        at Main$.init(Main.scala:8)
        at scalafx.application.AppHelper3.start(AppHelper3.scala:33)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.media.MediaPlayer$Status
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
        ... 30 more
```

**Comment by anh977** [comment]
Using sbt, I get the same warning/error.  It comes out as an error wrapping the warning in sbt.  I found it of course comes from javafx making note that it was loaded from the classpath rather than the modulepath. I'm using the ScalaFX Tutorial code. I've tried all the examples elsewhere mentioning this warning, using the map technique to specify modules, not using the map technique, but those add to libraryDependencies which still comes from the classpath, correct? I tried to manipulate the forked jvm with --add-modules, but it seems to require a jar with a main class on the modulepath.

Is there some way to either suppress the warning or otherwise make it go away?

**Comment by jpsacha** [comment]
If running application from within SBT you get a runtime warning:
```
   [error] ... com.sun.javafx.application.PlatformImpl startup
   [error] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module ...'
```
You can suppress the warning by adding the following to  SBT's project configuration:
```scala
Compile / run / javaOptions ++= Seq(
  "--module-path", (Compile / dependencyClasspath).value
                                                  .files
                                                  .filter(_.name.toLowerCase.contains("javafx"))
                                                  .mkString(java.io.File.pathSeparator),
  "--add-modules", "javafx.graphics",
  "--enable-native-access=javafx.graphics"
)
```
