### ISSUE TITLE
Demo scalafx.controls.TextAreaTest crashes with NPE

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#59]
_From [jpsacha](https://code.google.com/u/jpsacha/) on April 26, 2013 00:39:37_

Demo scalafx.controls.TextAreaTest crashes with exception:

Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:403)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
	at scalafx.scene.Node$.sfxNode2jfx(Node.scala:64)
	at scalafx.scene.layout.BorderPane.center_$eq(BorderPane.scala:84)
	at scalafx.controls.TextAreaTest$$anon$4.<init>(TextAreaTest.scala:81)
	at scalafx.controls.TextAreaTest$.mainPane$lzycompute(TextAreaTest.scala:79)
	at scalafx.controls.TextAreaTest$.mainPane(TextAreaTest.scala:79)
	at scalafx.controls.TextAreaTest$$anon$9$$anon$10.<init>(TextAreaTest.scala:60)
	at scalafx.controls.TextAreaTest$$anon$9.<init>(TextAreaTest.scala:58)
	at scalafx.controls.TextAreaTest$delayedInit$body.apply(TextAreaTest.scala:54)
...

The problem was introduced after M2 but before M3.

_Original issue: http://code.google.com/p/scalafx/issues/detail?id=59_

**Comment by jpsacha** [comment]
Cannot reproduce.
