### ISSUE TITLE
SFX-8: `ColorfulCircles` and  `SimpleColorfulCircles` demos fail

### ISSUE THREAD

**Issue by jpsacha** [scalafx/scalafx#69]
_From [jpsacha](https://code.google.com/u/jpsacha/) on July 30, 2013 22:49:44_

scalafx.ColorfulCircles and SimpleColorfulCircles fail with StackOverflowError in ScalaFX 8. Tested with Java 8 ea b100.

Part of the error message and stack trace is below (full message and trace are very long): 

com.sun.javafx.binding.SelectBinding$SelectBindingHelper getObservableValue
WARNING: Exception while evaluating select-binding [width]
com.sun.javafx.binding.SelectBinding$SelectBindingHelper getObservableValue
WARNING: Exception while evaluating select-binding [width]
com.sun.javafx.binding.SelectBinding$SelectBindingHelper getObservableValue
WARNING: Exception while evaluating select-binding [width]
...
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:867)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.StackOverflowError
	at com.sun.javafx.binding.SelectBinding$SelectBindingHelper.getObservableValue(SelectBinding.java:481)
	at com.sun.javafx.binding.SelectBinding$AsDouble.computeValue(SelectBinding.java:190)
	at javafx.beans.binding.DoubleBinding.get(DoubleBinding.java:203)
	at javafx.beans.property.DoublePropertyBase.get(DoublePropertyBase.java:133)
	at javafx.scene.shape.Rectangle.getWidth(Rectangle.java:235)
	at javafx.scene.shape.Rectangle.toString(Rectangle.java:564)
	at java.lang.String.valueOf(String.java:2985)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at javafx.beans.property.ReadOnlyObjectProperty.toString(ReadOnlyObjectProperty.java:69)
	at java.lang.String.valueOf(String.java:2985)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.sun.javafx.binding.SelectBinding$SelectBindingHelper.getObservableValue(SelectBinding.java:501)
	at com.sun.javafx.binding.SelectBinding$AsDouble.computeValue(SelectBinding.java:190)
	at javafx.beans.binding.DoubleBinding.get(DoubleBinding.java:203)
	at javafx.beans.property.DoublePropertyBase.get(DoublePropertyBase.java:133)
	at javafx.scene.shape.Rectangle.getWidth(Rectangle.java:235)
	at javafx.scene.shape.Rectangle.toString(Rectangle.java:564)
	at java.lang.String.valueOf(String.java:2985)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at javafx.beans.property.ReadOnlyObjectProperty.toString(ReadOnlyObjectProperty.java:69)
	at java.lang.String.valueOf(String.java:2985)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
...

_Original issue: http://code.google.com/p/scalafx/issues/detail?id=69_

**Comment by jpsacha** [comment]
Here is my understanding what is happening and and a suggested resolution. To focus on the key problem consider following simplified but complete code:

```scala
import scalafx.Includes._
import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage
import scalafx.scene.Scene
import scalafx.scene.paint.Color
import scalafx.scene.shape.Rectangle

object Issue69Tester extends JFXApp {
  stage = new PrimaryStage {
    scene = new Scene {
      content = new Rectangle {
        width <== scene.width
        height <== scene.height
        fill = Color.Black
      }
    }
  }
}
```

Running this resulted in StackOverflowError in line `width <== scene.width`.

Pay attention to `scene.width`. Notice that `scene` is of type `ReadOnlyObjectProperty[jfx.Scene]`. It is a property of the `stage`. At the moment line `width <== scene.width` is executed, the `scene` property value has not yet boon assigned. There is a trick that supposed to allow it to work. Notice that since `scene` is a `ReadOnlyObjectProperty` it does not have method `width`. There is an implicit conversion applied that converts `scene` property to `scalafx.scene.SceneProperty`. The idea behind `SceneProperty` was to "...enables the reading of properties of the scene that will be set into the property later on". The implementation looks something like this:

```scala
class SceneProperty(override val delegate: jfxbp.ReadOnlyObjectProperty[jfxs.Scene]) extends ... {
...
  def width = jfxbb.Bindings.selectDouble(delegate, "width")
...
}
```

This somehow worked in JavaFX 2. Actual scene this supposed to be the value of the `delegate` property, but that value is not yet assigned. That call to `selectDouble` is not really legitimate, it is passing in an invalid argument that should have correct value only sometime later. While it somehow worked in JavaFX 2, in JavaFX 8 things changed and that call results in `StackOverflowError`. JavaFX 8 is trying to find a `width` property but its stating point is not yet a valid property.

I think that `SceneProperty` should be removed as its use leads to problems.

My fix for the code above would be to use direct reference to the constructed scene (a named `this` of a scene). I name the reference, as  `_scene`, so it can be easily accessed from nested objects like `Rectangle`. Here is the corrected code

```scala
import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage
import scalafx.scene.Scene
import scalafx.scene.paint.Color
import scalafx.scene.shape.Rectangle

object Issue69WorkaroundTester extends JFXApp {
  stage = new PrimaryStage {
    scene = new Scene { _scene =>
      content = new Rectangle {
        width <== _scene.width
        height <== _scene.height
        fill = Color.Black
      }
    }
  }
}
```

It looks quite similar to original.

By the way there is also `scalafx.scene.control.TextFieldProperty` that should be removed too, for the same reason as `SceneProperty.

**Comment by jpsacha** [comment]
Looks that it was closed by mistake.
